version: '2.3'
services:    
  apiServer: 
    build: .
    image: mygo
    restart: always
    ports:
      - "443:443"
      - "80:80"
    working_dir: /go/src/vincent.com/golangginrest
    volumes:
      - ./:/go/src/vincent.com/golangginrest
    links:
      - gomysql
      - goredis
    command: "go run -v main.go"
  gomysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./backup:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
  goredis:
    image: redis
    restart: always
    ports:
      - "6379:6379"