version: '2.3'
services:    
  apiServer: 
    image: golang:1.10
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    working_dir: /go/src/vincent.com/golangginrest
    volumes:
        - ./:/go/src/vincent.com/golangginrest
    command: "go run main.go"
  gomysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./backup:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw