---
mysql:
  host: gomysql
  port: 3306
  dbname: test
  username: root
  password: my-secret-pw
  MaxIdelConns: 50
  maxOpenConns: 1000
  connMaxLifetime: 5
redis:
  host: goreids
  port: 6379
  password:
jwt:
  secret: secret
  expire: 60