// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-03-26 14:52:43.354034444 +0800 CST m=+0.048806068

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a sample server celler server.",
        "title": "Swagger Example API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "paths": {
        "/todo": {
            "post": {
                "description": "create a todo item with title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "create a todo item",
                "operationId": "create-to-do",
                "parameters": [
                    {
                        "description": "new todo item",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.TodoModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/todoctrl.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.TodoModel": {
            "type": "object",
            "properties": {
                "Completed": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "todoctrl.Response": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string"
                },
                "ResourceID": {
                    "type": "integer"
                },
                "Status": {
                    "type": "integer"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
